from typing import Protocol


class MarketDataProvider(Protocol):
    """Provider boundary for live and deterministic market data sources."""

    """Boundary for a real market data provider; no provider is active in Phase 1."""

    async def get_quote(self, symbol: str) -> object: ...
    async def get_historical_prices(self, symbol: str, range_name: str) -> object: ...
    async def get_volume(self, symbol: str, range_name: str) -> object: ...
    async def get_market_status(self) -> object: ...
